Title: 40323230日誌 - 105/07/22
Date: 2016-07-22 19:00
Category: 2016bg2
Tags: SWIG, Solvespace, CDemo, Python-Solvespace
Author: 40323230


1. Python-Solvespace編譯完畢。

2. 進行`_slvs.so`呼叫測試。

3. 公開倉儲[python-solvespace](https://github.com/40323230/python-solvespace"github.com")已推送。

<!-- PELICAN_END_SUMMARY -->

<h2>編譯成功 :</h2>

上次編譯時一直找不到`Slvs_`相關名稱的問題。

最後發現編譯`_slvs.so`時加入參照`libslvs.so`資料庫的指令（`-L`和`-l`），就成功編譯了。

結束編譯時，Makefile執行了CDemo.exe證明C語言調用`libslvs.so`是完全沒問題的。

<img src="http://i.imgur.com/M7G0AH3.jpg" >

接著要試著執行Python調用`_slvs.so`。

<hr>

<h2>測試test.py和Usage.py :</h2>

作者提供了2個範例使用，將它們和`_slvs.so`放在相同目錄中。

`Usage.py`是參照Readme的說明，將範例code抓下來存在`exposed`資料夾的程式檔。

然而若直接執行會出下列錯誤：

*test.py*
--------------

<img src="http://i.imgur.com/Dp86EeP.jpg" >

*Usage.py*
--------------

<img src="http://i.imgur.com/goKX3du.jpg" >

意思是Python無法調用`_slvs`這個模組，大部分的原因是名稱錯誤或是沒有導入。

SWIG手冊的"Using distutils"之後的幾章是講導出模組後的應用。

<img src="http://i.imgur.com/xm3XyRs.jpg" >

看了一下內容，Python導出後的模組可以作為Python的附加元件、直接呼叫、動態模組、靜態連結之類的。

不過沒有解答一些例外的錯誤。

但是一直找不到`_slvs.so`，不知道是出了甚麼問題，會繼續尋找資料。

<hr>

<h2>公開倉儲 :</h2>

把目前進度推到了自己的[python-solvespace](https://github.com/40323230/python-solvespace"github.com")倉儲，在`exposed`資料夾中的Makefile編輯工具位置，就能Make和Clean。

<img src="http://i.imgur.com/u5OAbuX.jpg" >